import js from "@eslint/js";
import ts from "typescript-eslint";
import vue from "eslint-plugin-vue";
export default ts.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      ".netlify/**",
      "playwright-report/**",
      "test-results/**",
    ],
  },
  js.configs.recommended,
  ...ts.configs.recommended,
  ...vue.configs["flat/essential"],
  {
    files: ["**/*.vue"],
    languageOptions: {
      parserOptions: { parser: ts.parser, extraFileExtensions: [".vue"] },
    },
  },
  {
    languageOptions: {
      globals: Object.fromEntries(
        [
          "window",
          "document",
          "location",
          "navigator",
          "localStorage",
          "indexedDB",
          "crypto",
          "fetch",
          "performance",
          "console",
          "setTimeout",
          "clearTimeout",
          "setInterval",
          "clearInterval",
          "AbortController",
          "AbortSignal",
          "URL",
          "URLSearchParams",
          "TextEncoder",
          "TextDecoder",
          "Response",
          "Request",
          "Headers",
          "Blob",
          "File",
          "HTMLElement",
          "HTMLInputElement",
          "HTMLSelectElement",
          "HTMLDialogElement",
          "HTMLTextAreaElement",
          "HTMLAnchorElement",
          "Element",
          "Node",
          "DOMException",
          "CustomEvent",
          "Event",
          "KeyboardEvent",
          "MouseEvent",
          "ResizeObserver",
          "IntersectionObserver",
          "requestAnimationFrame",
          "cancelAnimationFrame",
          "atob",
          "btoa",
          "structuredClone",
          "process",
          "Buffer",
        ].map((name) => [name, "readonly"]),
      ),
    },
    rules: {
      "no-undef": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "vue/multi-word-component-names": "off",
    },
  },
);
